name: MarbleMobile
options:
  bundleIdPrefix: com.example.marble
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    SWIFT_VERSION: 5.0
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "RHWMV6VVZ6"
targets:
  MarbleMobileCore:
    type: framework
    platform: iOS
    sources:
      - Sources/MarbleMobileCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.marble.core
        SKIP_INSTALL: YES
        GENERATE_INFOPLIST_FILE: YES
  MarbleMobile:
    type: application
    platform: iOS
    sources:
      - iOS/MarbleMobile
    dependencies:
      - target: MarbleMobileCore
    info:
      path: iOS/MarbleMobile/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jsj.marble.mobile
        PRODUCT_NAME: MarbleMobile
